# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SquareTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SkeletonView'

  # Pods for SquareTest

  target 'SquareTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SquareTestUITests' do
    # Pods for testing
  end

end
